version: "3.9"
services:
    terhelper:
        build: ./apps/terhelper
        command: "mvn install -Pprod"
        depends_on:
            - "redis"
            - "tomcat"
            - "nginx"
        volumes: 
            - ./volumes/tomcat/webapps:/docker_apps/volumes/tomcat/webapps
            - ./apps/terhelper:/sites/terhelper
    redis:
        build:
            context: ./redis
            dockerfile: Dockerfile-redis
        ports: 
            - "127.0.0.1:6379:6379"
        restart: always
        volumes:
            - ./volumes/redis/data:/data
    tomcat:
        image: "tomcat:8.5.71-jdk17-temurin-focal"
        ports: 
            - "127.0.0.1:8080:8080"
        restart: always
        volumes: 
            - ./volumes/tomcat/webapps:/usr/local/tomcat/webapps
            - ./apps/terhelper:/sites/terhelper
    nginx:
        image: "nginx:1.15-alpine"
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes: 
            - ./volumes/certbot/conf:/etc/letsencrypt
            - ./volumes/certbot/www:/var/www/certbot
            - ./nginx/conf.d:/etc/nginx/conf.d
    certbot:
        image: "certbot/certbot"
        volumes:
            - ./volumes/certbot/conf:/etc/letsencrypt
            - ./volumes/certbot/www:/var/www/certbot
            
networks:
    default:
        name: nginx_net
